### ISSUE TITLE
[Suggession] Doggy Talents Textures

### ISSUE THREAD

**Issue by NovaViper** [FaithfulTeam/ModdedFaithful#9]
Hey, I would love to see this resourcepack support [Doggy Talents](https://minecraft.curseforge.com/projects/doggy-talents?gameCategorySlug=mc-mods&projectID=271050) ^^

**Comment by MarikCZ** [comment]
I have started modpack project The Digital Age, and last update is 14 days
out - Maybe in the future 🔮 , at the moment I have not time ⌚.

Dne 6. 7. 2017 2:25 AM napsal uživatel "Nova Leary" <
notifications@github.com>:

**Comment by NovaViper** [comment]
Ah, that's cool! Hopefully things go well for the modpack ^^ I was doing some searching around and found that someone indeed created [textures for Doggy Talents](https://minecraft.curseforge.com/projects/faithful-32x32-for-doggy-talents) for the Faithful resourcepack. When I get the chance, I'll start updating the pack :D

**Comment by MarikCZ** [comment]
OK ✅ That's good...

Dne 6. 7. 2017 19:12 napsal uživatel "Nova Leary" <notifications@github.com

**Comment by NovaViper** [comment]
I just finished updating the texture names for the mod's current version.. I'll start a pull request ^_^

**Comment by NovaViper** [comment]
Just created pull request #10!

**Comment by NovaViper** [comment]
Uh.. Now I need some new textures ._. The developer has changed **ALOT** with the textures of the dogs with the addition of the Wool Collars (which is cool not going to lie :D). I'm going to convert over some of the already created textures.. however I need some new collar textures, they're on the front cover of the mod page: https://minecraft.curseforge.com/projects/doggy-talents
